/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NEW_USER;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel Chacon
 */
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/Form_New_User.java
public class Form_New_User extends javax.swing.JInternalFrame {

    
   
=======
public class UserNew extends javax.swing.JFrame {
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UserNew.java
    private static String db = "NOMINA_SALARIO";
    private static String user = "root";
    private static String password = "compromiso";
    private static String host = "localhost";
    private static String server = "jdbc:mysql://"+ host + "/" +db; 
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/Form_New_User.java
    
    public Form_New_User() {
=======
    /**
     * Creates new form UserNew
     */
    public UserNew() {
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UserNew.java
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        txt_Password = new javax.swing.JPasswordField();
        btnClose = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("          CREATE A NEW ACCOUNT ");

        jLabel2.setText("USER NAME ");

        jLabel3.setText("PASSWORD");

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnRegreso.setText("RETURN");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_User, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(txt_Password))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        // TODO add your handling code here:
        /* ventanaUsuarios = new Form_Logiin_Users();
        jDesktopPane1.add(ventanaUsuarios);*/
    }//GEN-LAST:event_btnRegresoActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        if ( txt_User.getText().isEmpty() || txt_Password.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, " NO PUEDE DEJAR CAMPOS VACIOS ");

            txt_User.setText("");
            txt_Password.setText("");
        }
        else {

            try{
                Connection cn = DriverManager.getConnection(server, user, password);
                PreparedStatement pst = cn.prepareStatement("insert into USUARIOS values(?,?,?)");
                //en la variables pst de tipo coneccion a base de datos inserte
                // pst.setString(1, "0");
                pst.setString(1, "0");
                pst.setString(2, txt_User.getText().trim());
                pst.setString(3, txt_Password.getText().trim());
                pst.executeUpdate();
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/Form_New_User.java
                JOptionPane.showMessageDialog(null, " USUARIO REGISTRADO CORRECTAMENTE");
                
                
                    LOGIN_USUARIOS ventana = new LOGIN_USUARIOS();
                    jDesktopPane1.add(ventana);
=======
                
                JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO CORRECTAMENTE");
                
                UsersLogin ventana = new UsersLogin();
                ventana.setVisible(true);
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UserNew.java

                txt_User.setText("");
                txt_Password.setText("");

                this.dispose();
            }catch (Exception e){

            }
        }

        //  pst.setString(4, txt_ConfirmPassword.getText().trim());

        /*if (txt_Password != txt_ConfirmPassword){

            JOptionPane.showMessageDialog(null, " LOS CAMPOS NO SON IGUALES");
            // JOptionPane.showMessageDialog(null, " USUARIO REGISTRADO CORRECTAMENTE");
            txt_Password.setText("");
            txt_ConfirmPassword.setText("");
            //dispose();

        }else  {
            //(txt_Password == txt_ConfirmPassword){
                >>>>>>> 97bf503d41cebc4b1398fb20f6ada3cf0fdeaae9:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/Form_New_User.java

                JOptionPane.showMessageDialog(null, " USUARIO REGISTRADO CORRECTAMENTE");
                dispose();
                //JOptionPane.showMessageDialog(null, " LOS CAMPOS NO SON IGUALES");
                // txt_Password.setText("");
                // txt_ConfirmPassword.setText("");
            }*/

            // aca ejecuta el qvery
            //JOptionPane.showMessageDialog(null, " USUARIO REGISTRADO CORRECTAMENTE");

            ///txt_ConfirmPassword.setText("");

            /*  pst.executeUpdate();
            Form_Logiin_Users usuario = new Form_Logiin_Users();
            usuario.setVisible(true);

            txt_User.setText("");
            txt_Password.setText("");

            // limpiio registros
            // txt_User.setText("");
            // txt_Password.setText("");
            //txt_ConfirmPassword.setText("");

            // label_status.setText("USUARIO REGISTRADO EXITOSAMENTE.");
        }catch (Exception e){

        }
        }*///
        /*}else {
        JOptionPane.showMessageDialog(null, " LOS CAMPOS NO SON IGUALES");
        txt_Password.setText("");
        txt_ConfirmPassword.setText("");
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables
}
