/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NEW_USER;
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java

/*import static ACCESO_ADMINISTRADOR.Form_Acceso_Admin.password;
import static ACCESO_ADMINISTRADOR.Form_Acceso_Admin.server;
import static ACCESO_ADMINISTRADOR.Form_Acceso_Admin.user;*/
import ACCESO_USUARIOS.VISTA_USUARIO;
import java.awt.Dimension;
=======
import PLANILLA_FASE2.Form_Pantalla_Ingreso;
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Angel Chacon
 */
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
public class LOGIN_USUARIOS extends javax.swing.JInternalFrame {

    

=======
public class UsersLogin extends javax.swing.JFrame {
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java
    private static String db = "NOMINA_SALARIO";
<<<<<<< HEAD
    private static String user = "rex";
    private static String password = "polloloco900";
=======
    private static String user = "root";
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
    private static String password = "Cagada1234";
>>>>>>> Sebastian
    private static String host = "localhost";
    private static String server = "jdbc:mysql://"+ host + "/" +db; 
    
    
    
    
    
    
=======
    private static String password = "compromiso";
    private static String host = "localhost";
    private static String server = "jdbc:mysql://"+ host + "/" +db; 
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java
    /**
     * Creates new form UsersLogin
     */
    public UsersLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
        txtUsuario = new javax.swing.JTextField();
        btnNuevoUsuario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
=======
        btnIngresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNuevoUsuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtUsuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("USER LOGIN");

        fondo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NEW_USER/fondo_ingreso_users.png"))); // NOI18N

        txtPass.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
        txtUsuario.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        btnNuevoUsuario.setText("NUEVO USUARIO");
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
=======
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });

<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
=======
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NEW_USER/fondo login users.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");

        btnNuevoUsuario.setText("NUEVO USUARIO");
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
=======
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtPass)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java
                        .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fondo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(fondo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnNuevoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
=======
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed

        
Form_New_User ventana = new Form_New_User();
jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.show();

// TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if ( txtUsuario.getText().isEmpty() || txtPass.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, " NO SE PUEDE DEJAR CAMPOS VACIOS");

            txtUsuario.setText("");
            txtPass.setText("");
        }
        else {

            try{

                Connection cn = DriverManager.getConnection(server, user, password);

<<<<<<< HEAD
                PreparedStatement pst = cn.prepareStatement("select * from USUARIOS where NombreUsuario = ?");
=======
                PreparedStatement pst = cn.prepareStatement("select * from USUARIOS where Usuario = ?");
>>>>>>> Sebastian

                pst.setString(1, txtUsuario.getText().trim());
                ResultSet rs = pst.executeQuery();

<<<<<<< HEAD
                PreparedStatement pst2 = cn.prepareStatement("select * from USUARIOS where Pass = ?");
=======
                PreparedStatement pst2 = cn.prepareStatement("select * from USUARIOS where pass = ?");
>>>>>>> Sebastian

                pst2.setString(1, txtPass.getText().trim());
                ResultSet rs2 = pst2.executeQuery();

                if(rs.next()){

                    if(rs2.next()){
                        JOptionPane.showMessageDialog(null, "Bienvenido" + "    " + rs.getString("Usuario"));

                       VISTA_USUARIO ventana = new VISTA_USUARIO();
                       ventana.setVisible(true);
                       

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "No registrado.");
                    txtUsuario.setText("");
                    txtPass.setText("");

=======
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try{
            
            Connection cn = DriverManager.getConnection(server, user, password);
            PreparedStatement pst = cn.prepareStatement("select * from USUARIOS where NombreUsuario = ?");
            
            
            pst.setString(1, txtUsuario.getText().trim());
            ResultSet rs = pst.executeQuery();
            
            PreparedStatement pst2 = cn.prepareStatement("select * from USUARIOS where Pass = ?");
            
            
            pst2.setString(1, txtPass.getText().trim());
            ResultSet rs2 = pst2.executeQuery();
            
            if(rs.next()){
                
                txtUsuario.setText(rs.getString("NombreUsuario"));
                
                if(rs2.next()){
                
                txtPass.setText(rs.getString("Pass"));
                
                 JOptionPane.showMessageDialog(null, "Registrado.");
                
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "No registrado.");
            }
<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java

<<<<<<< HEAD
=======
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Error no registrado.");
            
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed

<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
        
Form_New_User ventana = new Form_New_User();
jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.show();
=======
        UserNew ventana = new UserNew();
        ventana.setVisible(true);
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

<<<<<<< HEAD:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/LOGIN_USUARIOS.java
=======
    }//GEN-LAST:event_jButton1ActionPerformed
    }
>>>>>>> Sebastian
=======
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersLogin().setVisible(true);
            }
        });
    }
>>>>>>> 3dfea1a58a2ae788c3591b25e5a4c6fa6848458f:NOMINA_FASE2_SQL/PLANILLA_FASE2_SQL/src/NEW_USER/UsersLogin.java

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
