/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ACCESO_ADMINISTRADOR;

/**
 *
 * @author Angel Chacon
 */
public class ACCION extends javax.swing.JFrame {

    /**
     * Creates new form ACCION
     */
    public ACCION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAcceso = new javax.swing.JMenu();
        jMenupuestos = new javax.swing.JMenuItem();
        jMenuConceptos = new javax.swing.JMenuItem();
        jMenuRegistrarEmpleado = new javax.swing.JMenuItem();
        jMenuCalculosSueldos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuRegresar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuAcceso.setText("ACCESOS");

        jMenupuestos.setText("PUESTOS");
        jMenupuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenupuestosActionPerformed(evt);
            }
        });
        jMenuAcceso.add(jMenupuestos);

        jMenuConceptos.setText("CONCEPTOS");
        jMenuConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConceptosActionPerformed(evt);
            }
        });
        jMenuAcceso.add(jMenuConceptos);

        jMenuRegistrarEmpleado.setText("REGISTRAR EMPLEADO ");
        jMenuRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jMenuAcceso.add(jMenuRegistrarEmpleado);

        jMenuCalculosSueldos.setText("CALCULOS SUELDOS");
        jMenuCalculosSueldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalculosSueldosActionPerformed(evt);
            }
        });
        jMenuAcceso.add(jMenuCalculosSueldos);

        jMenuItem2.setText("CONSULTA PLANILLA");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAcceso.add(jMenuItem2);

        jMenuBar1.add(jMenuAcceso);

        jMenuRegresar.setText("REGRESAR");

        jMenuItem1.setText("SALIR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRegresar.add(jMenuItem1);

        jMenuBar1.add(jMenuRegresar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrarEmpleadoActionPerformed

        Registro ventana = new Registro ();
        jDesktopPane1.add(ventana);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRegistrarEmpleadoActionPerformed

    private void jMenuCalculosSueldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalculosSueldosActionPerformed
        // TODO add your handling code here:

        Form_Acceso_Admin ventana = new  Form_Acceso_Admin ();
        jDesktopPane1.add(ventana);
    }//GEN-LAST:event_jMenuCalculosSueldosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenupuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenupuestosActionPerformed
        // TODO add your handling code here:
        IngresoPuestos ventanap = new  IngresoPuestos ();
        jDesktopPane1.add(ventanap);
        
    }//GEN-LAST:event_jMenupuestosActionPerformed

    private void jMenuConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConceptosActionPerformed
        // TODO add your handling code here:
        CONCEPTO ventana = new  CONCEPTO();
        jDesktopPane1.add(ventana);
        
    }//GEN-LAST:event_jMenuConceptosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ADMIN_CONCEPTOS ventana = new  ADMIN_CONCEPTOS();
        jDesktopPane1.add(ventana);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACCION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuAcceso;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCalculosSueldos;
    private javax.swing.JMenuItem jMenuConceptos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuRegistrarEmpleado;
    private javax.swing.JMenu jMenuRegresar;
    private javax.swing.JMenuItem jMenupuestos;
    // End of variables declaration//GEN-END:variables
}
