/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ACCESO_ADMINISTRADOR;

import NEW_USER.LOGIN_ADMI;
import NEW_USER.LOGIN_USERS;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author Geovani
 */
public class VISTA_ADMINISTRADOR extends javax.swing.JFrame {

    /**
     * Creates new form VISTA_ADMINISTRADOR
     */
    public VISTA_ADMINISTRADOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_SueldoExtraOrdinario = new javax.swing.JTextField();
        txt_Bonificacion = new javax.swing.JTextField();
        txt_Comision = new javax.swing.JTextField();
        txt_OtrosDevengados = new javax.swing.JTextField();
        btn_Modificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        txtTotalDevengados = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txtCodPuesto = new javax.swing.JTextField();
        txtCodDepartamento = new javax.swing.JTextField();
        PANTALLA_TRASERA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(7);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Guardar.setText("GUARDAR");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 100, 40));

        jLabel1.setText("CALCULOS PLANILLA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 110, 60));

        jLabel4.setText("SUELDO EXTRAORDINARIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, 30));

        jLabel5.setText("BONIFICACION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 30));

        jLabel6.setText("COMISIONES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, 30));

        jLabel7.setText("OTROS DEVENGADOS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 160, 30));

        jLabel9.setText("SUELDO ORDINARIO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, 30));

        jLabel10.setText("NOMBRE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 30));

        jLabel11.setText("COD. PUESTO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 30));
        getContentPane().add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 210, 30));
        getContentPane().add(txt_SueldoExtraOrdinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 210, 30));
        getContentPane().add(txt_Bonificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 210, 30));
        getContentPane().add(txt_Comision, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 210, 30));
        getContentPane().add(txt_OtrosDevengados, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 210, 30));

        btn_Modificar.setText("MODIFICAR");
        getContentPane().add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 90, 40));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 100, 40));

        btn_Buscar.setText("BUSCAR");
        getContentPane().add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 100, 40));

        btn_Eliminar.setText("ELIMNAR");
        getContentPane().add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 90, 40));
        getContentPane().add(txtTotalDevengados, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 210, 30));

        jLabel12.setText("TOTAL DEVENGADOS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 120, 30));

        jLabel13.setText("COD. DEPARTAMENTO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel15.setText("ESTADO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 210, 30));
        getContentPane().add(txtCodPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, 30));
        getContentPane().add(txtCodDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, 30));
        getContentPane().add(PANTALLA_TRASERA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 660, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        LOGIN_USERS regreso = new LOGIN_USERS();
        regreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        // TODO add your handling code here:
        
        
        
        
       
    }//GEN-LAST:event_btn_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VISTA_ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VISTA_ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VISTA_ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VISTA_ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VISTA_ADMINISTRADOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PANTALLA_TRASERA;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtCodDepartamento;
    private javax.swing.JTextField txtCodPuesto;
    private javax.swing.JTextField txtTotalDevengados;
    private javax.swing.JTextField txt_Bonificacion;
    private javax.swing.JTextField txt_Comision;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_OtrosDevengados;
    private javax.swing.JTextField txt_SueldoExtraOrdinario;
    // End of variables declaration//GEN-END:variables
}
