/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PLANILLA_FASE2;
import NEW_USER.LoginAdmin;
import NEW_USER.UsersLogin;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
/**
 *
 * @author Angel Chacon
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIngresoAdmi = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuDepartamento = new javax.swing.JMenuItem();
        jMenuPuesto = new javax.swing.JMenuItem();
        jMenuConceptos = new javax.swing.JMenuItem();
        jMenuEmpleados = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuExtras = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuFinal = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuCalculos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuinfor = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);

        jDesktopPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDesktopPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jMenu1.setText("Ingresar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuIngresoAdmi.setText("Administrador");
        jMenuIngresoAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresoAdmiActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIngresoAdmi);

        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuUsuarios);

        jMenuBar3.add(jMenu1);

        jMenu5.setText("Catalogos");

        jMenuDepartamento.setText("Departamento");
        jMenu5.add(jMenuDepartamento);

        jMenuPuesto.setText("Puesto");
        jMenu5.add(jMenuPuesto);

        jMenuConceptos.setText("Conceptos");
        jMenu5.add(jMenuConceptos);

        jMenuEmpleados.setText("Empleados");
        jMenu5.add(jMenuEmpleados);

        jMenuBar3.add(jMenu5);

        jMenu6.setText("Procesos");

        jMenuExtras.setText("Nomina Extras");
        jMenu6.add(jMenuExtras);

        jMenuBar3.add(jMenu6);

        jMenu7.setText("Informes");

        jMenuFinal.setText("Nomina Final");
        jMenu7.add(jMenuFinal);

        jMenuBar3.add(jMenu7);

        jMenu9.setText("Herramientas");

        jMenuCalculos.setText("Calculos");
        jMenu9.add(jMenuCalculos);

        jMenuBar3.add(jMenu9);

        jMenu8.setText("Ayuda");

        jMenuinfor.setText("Informacion");
        jMenu8.add(jMenuinfor);

        jMenuSalir.setText("Salir");
        jMenu8.add(jMenuSalir);

        jMenuBar3.add(jMenu8);

        jMenu2.setText("Salir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jSalir);

        jMenuBar3.add(jMenu2);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDesktopPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDesktopPane1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPane1AncestorAdded

    private void jMenuIngresoAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresoAdmiActionPerformed

        LoginAdmin ventanaLoginAdmin = new LoginAdmin();
        ventanaLoginAdmin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIngresoAdmiActionPerformed

    private void jMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosActionPerformed
        // TODO add your handling code here:
        UsersLogin ventanaLoginUsuarios = new UsersLogin();
        ventanaLoginUsuarios.setVisible(true);
    }//GEN-LAST:event_jMenuUsuariosActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuCalculos;
    private javax.swing.JMenuItem jMenuConceptos;
    private javax.swing.JMenuItem jMenuDepartamento;
    private javax.swing.JMenuItem jMenuEmpleados;
    private javax.swing.JMenuItem jMenuExtras;
    private javax.swing.JMenuItem jMenuFinal;
    private javax.swing.JMenuItem jMenuIngresoAdmi;
    private javax.swing.JMenuItem jMenuPuesto;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jMenuUsuarios;
    private javax.swing.JMenuItem jMenuinfor;
    private javax.swing.JMenuItem jSalir;
    // End of variables declaration//GEN-END:variables
}
